#! /bin/bash

echo <<EOF
##### adduser ##### by Wilson Lisan v1.0
Scripting untuk menambah user baru pada semua node.
Cara menggunakan:
1. Edit variable basename, masternode, bawah, dan atas
2. Masukkan nama user saat diminta oleh program
2. Syntax: ./adduser
EOF

# Masukkan nama hostname cluster tanpa index angka
basename=polarbear

# Masukkan nama hostname node master
masternode=${basename}1

# Masukkan indeks node slave
bawah=2
atas=3

# Memastikan sys-admin sudah menyesuaikan variabel diatas untuk mesinnya
echo "Apakah daftar hostname node dibawah ini sudah benar untuk penambahan user baru di kluster Anda?"
echo "MASTER	:${masternode}"
echo "SLAVE	:${basename}$bawah - ${basename}$atas"

while true; do
	read -p "y/n:" answer
	case $answer in
		[n] ) echo "Silahkan edit variabel nama hostname dan index yang mau ditambah user di script adduser"; exit;;
		[y] ) break;;
		* ) echo "Tolong jawab dengan y (yes) atau n (no)";;
	esac
done

# Program berhenti ketika ada argumen yang dimasukkan
if [ $# -gt 0 ]
then
	echo "Tidak ada argumen"
	exit
fi

# Membuat user
echo "Masukkan nama user baru:"
read username

# Cek apakah user yang ada dibuat sudah diambil namanya atau belum 
if id "$username" >/dev/null 2>&1; then
	echo "User $username sudah ada, masukkan nama user lain"
	exit
else
	:
fi

# Membuat user baru di node master 
echo "----- Membuat user $username di node ${masternode} -----"
sudo adduser $username
#sudo passwd $1 #pada rasbian adduser sudah otomatis input password
echo "===== User ${username} telah berhasil dibuat di node ${masternode}"

# Untuk memasukkan user baru ke sudo group, di rasbian harus manual di /etc/sudoers
# INGAT TANGGUNG JAWAB SYS-ADMIN untuk memasukkan user ke sudoers group!!!
# newuser	ALL=(ALL) ALL

# Membuat user baru di node slave 
for (( i=$bawah; i<=atas; i++ ))
do
	echo ""
	echo "Membuat user $username di node ${basename}$i"
	ssh ${basename}$i bash -c "'
	sudo adduser $username
	'"
	echo "===== User ${username} telah berhasil dibuat di node ${basename}$i"
done
