#! /bin/bash

echo <<EOF
##### passwordless-ssh ##### by Wilson Lisan v1.0
Scripting untuk setting passwordless-ssh pada semua node.
Cara menggunakan: 
1. Edit variable basename, masternode, bawah, dan atas
2. Buat file olala.txt pada direktori yang sama, berisikan password user
3. Syntax: ./passwordles-ssh
4. Bisa dijalankan di node slave ketika semua node slave ingin passwordless-ssh juga
EOF

# Masukkan nama hostname cluster tanpa index angka
basename=polarbear

# Masukkan nama hostname node master
masternode=${basename}1

# Masukkan indeks node slave yang ingin di passwordless-ssh
bawah=2
atas=3

# Memastikan sys-admin sudah menyesuaikan variabel diatas untuk mesinnya
echo "Apakah daftar hostname node dibawah sudah benar untuk prosesi passwordless ssh di kluster Anda?"
echo "MASTER	:${masternode}"
echo "SLAVE	:${basename}$bawah - ${basename}$atas"

while true; do
	read -p "y/n:" answer
	case $answer in
		[n] ) echo "Silahkan edit nama hostname dan index yang mau diprosesi passwordless ssh di script passwordless-ssh"; exit;;
		[y] ) break;;
		* ) echo "Tolong jawab dengan y (yes) atau n (no)";;

	esac
done

# Program berhenti ketika ada argumen yang dimasukkan
if [ $# -gt 0 ]
then
	echo "tidak ada argumen, cukup ./passwordless-ssh saja"
	exit
fi

echo "REMINDER: Script ini tidak mendukung reverse ssh-copy-id"
# Generate passwordless-ssh di semua node, hanya dilakukan di node master 
# Sebelumnya install sshpass: sudo apt-get//yum install sshpass

if [ "$HOSTNAME" = "${masternode}" ]
then
	# Cek apakah di node master sudah terbentuk ssh-keygen
	if [ ! -e ~/.ssh/id_rsa ]
	then
		echo "---------- Generate password di node $masternode"
		# Automatic passwordless ssh-keygen
		ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
	else
		echo "ssh-keygen di ${masternode} sudah terbentuk, skip ke generate authorized keys di node slave"
	fi
	
	# Generate authorized keys di node slave
	# Somehow tidak mau automatic ssh-keygen dari remote node master ._. 
	for (( i=$bawah; i<=$atas; i++ )) 
	do
		echo "---------- Generate authorized key di ${basename}$i"
		sshpass -f olala.txt ssh -o StrictHostKeyChecking=no ${basename}$i cat /dev/zero | ssh-keygen -q -N ""
	done
fi

# Generate id_rsa dan id_rsa.pub key khusus untuk node slave 
if [ "$HOSTNAME" != "${masternode}" ]
then
	echo "---------- Inisialisasi passwordless ssh-keygen"
	ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
fi

# Copy passwordless-ssh ke semua node termasuk dirinya sendiri
echo "---------- Passwordless SSH ke node $masternode"
sshpass -f olala.txt ssh-copy-id -o StrictHostKeyChecking=no $masternode -p 11211
for (( j=$bawah; j<=$atas; j++ ))
do
	echo "---------- Passwordless SSH di node ${basename}$j"
	sshpass -f olala.txt ssh-copy-id -o StrictHostKeyChecking=no ${basename}$j
done

# Menghapus olala.txt
rm olala.txt
